values = [
    "1st Colony, Mirpur, Dhaka",
    "2nd Colony, Mirpur, Dhaka",
    "3rd Colony, Mirpur, Dhaka",
    "Aainusbag, Dakshin Khan, Dhaka",
    "Abdul Aziz Lane, Lalbagh, Dhaka",
    "Abur Tek Road, Khilkhet, Dhaka",
    "Adarsha Nagar, Badda, Dhaka",
    "Advanced Police Town, Savar, Dhaka",
    "Aga Sadek Road, Bangshal, Dhaka",
    "Agamasi Lane, Bangshal, Dhaka",
    "Agargaon, Dhaka",
    "Ahmed Nagar, Mirpur, Dhaka",
    "Allabdirtec Road 1, Cantonment, Dhaka",
    "Alu Bazar, Bangshal, Dhaka",
    "Amligola, Lalbagh, Dhaka",
    "Amtola Masjid Goli Road, North Shahjahanpur, Dhaka",
    "Arambagh, Motijheel, Dhaka",
    "Asad Avenue, Mohammadpur, Dhaka",
    "Ashi Dag Road, Ibrahimpur, Dhaka",
    "Ashkona, Dakshin Khan, Dhaka",
    "Ashulia, Savar, Dhaka",
    "Ati Bazar, Keraniganj, Dhaka",
    "Atosh Khana Lane, Lalbagh, Dhaka",
    "Aurangzeb Road, Mohammadpur, Dhaka",
    "Azam Road, Mohammadpur, Dhaka",
    "Azimpur Road, Lalbagh, Dhaka",
    "Azimpur, Lalbagh, Dhaka",
    "aziz Moholla, Mohammadpur, Dhaka",
    "Babar Road, Mohammadpur, Dhaka",
    "Bagan Bari Road, Cantonment, Dhaka",
    "Bagicha Mashjid Road, North Shahjahanpur, Dhaka",
    "Baitul Aman Housing Society, Adabor, Dhaka",
    "Bakshi Bazar, Lalbagh, Dhaka",
    "Banasree Main Road, Banasree, Dhaka",
    "Bangshal Road, Bangshal, Dhaka",
    "Bank Colony, Savar, Dhaka",
    "Bank Town, Savar, Dhaka",
    "Bash Bari Road, Mohammadpur, Dhaka",
    "Bashabo Madartek Road, Bashabo, Dhaka",
    "Bashir Uddin Road, Kalabagan, Dhaka",
    "Bashundhara Road, Bashundhara R-A, Dhaka",
    "Bata Goli, Maghbazar, Dhaka",
    "Bawnia, Turag, Dhaka",
    "Becharam Dewri, Bangshal, Dhaka",
    "Bepari Goli, Maghbazar, Dhaka",
    "Bhagalpur, Hazaribag, Dhaka",
    "Bhatuliya, Turag, Dhaka",
    "Bibir Bagicha, Jatra Bari, Dhaka",
    "Block A, Aftab Nagar, Dhaka",
    "Block A, Banasree, Dhaka",
    "Block A, Bashundhara R-A, Dhaka",
    "Block A, Lalmatia, Dhaka",
    "Block A, Niketan, Dhaka",
    "Block B, Aftab Nagar, Dhaka",
    "Block B, Banasree, Dhaka",
    "Block B, Bashundhara R-A, Dhaka",
    "Block B, Lalmatia, Dhaka",
    "Block B, Niketan, Dhaka",
    "Block C Extension, Banasree, Dhaka",
    "Block C, Aftab Nagar, Dhaka",
    "Block C, Banasree, Dhaka",
    "Block C, Bashundhara R-A, Dhaka",
    "Block C, Khilgaon, Dhaka",
    "Block C, Lalmatia, Dhaka",
    "Block C, Niketan, Dhaka",
    "Block D, Aftab Nagar, Dhaka",
    "Block D, Banasree, Dhaka",
    "Block D, Bashundhara R-A, Dhaka",
    "Block D, Lalmatia, Dhaka",
    "Block D, Niketan, Dhaka",
    "Block E, Aftab Nagar, Dhaka",
    "Block E, Banasree, Dhaka",
    "Block E, Bashundhara R-A, Dhaka",
    "Block E, Lalmatia, Dhaka",
    "Block E, Niketan, Dhaka",
    "Block F, Aftab Nagar, Dhaka",
    "Block F, Banasree, Dhaka",
    "Block F, Bashundhara R-A, Dhaka",
    "Block F, Niketan, Dhaka",
    "Block G, Banasree, Dhaka",
    "Block G, Bashundhara R-A, Dhaka",
    "Block H, Banasree, Dhaka",
    "Block H, Bashundhara R-A, Dhaka",
    "Block I, Bashundhara R-A, Dhaka",
    "Block J, Banasree, Dhaka",
    "Block J, Baridhara, Dhaka",
    "Block J, Bashundhara R-A, Dhaka",
    "Block K, Baridhara, Dhaka",
    "Bochila, Mohammadpur, Dhaka",
    "Boro Maghbazar, Maghbazar, Dhaka",
    "Bosila, Mohammadpur, Dhaka",
    "Bot Tola, Khilkhet, Dhaka",
    "Central Road, Dhanmondi, Dhaka",
    "Chad Uddan Housing, Mohammadpur, Dhaka",
    "Chairman Para, Dakshin Khan, Dhaka",
    "Chamilibag, Shantinagar, Dhaka",
    "Chandrima Model Town, Mohammadpur, Dhaka",
    "Chawk Bazar, Lalbagh, Dhaka",
    "Chowdhuripara, Khilgaon, Dhaka",
    "Circular Road, Dhanmondi, Dhaka",
    "Comfort Housing, Adabor, Dhaka",
    "Comilla Para, Badda, Dhaka",
    "Crescent Road, Kathalbagan, Dhaka",
    "Dagormora, Savar, Dhaka",
    "Dakhshin Para, Mohakhali, Dhaka",
    "Dakkhin Paikpara, Mirpur, Dhaka",
    "Darussalam, Mirpur, Dhaka",
    "Dhaka Housing Main Road, Shyamoli, Dhaka",
    "Dhaka Uddan, Mohammadpur, Dhaka",
    "Dhalpur, Jatra Bari, Dhaka",
    "Dholpur New Road, Jatra Bari, Dhaka",
    "Dhour Mouza, Turag, Dhaka",
    "Dilkhushabag, Savar, Dhaka",
    "DIT Road, Malibagh, Dhaka",
    "Doctor Goli, Maghbazar, Dhaka",
    "Dolphin Goli Road, Kalabagan, Dhaka",
    "Donia, Jatra Bari, Dhaka",
    "Doniya, Shyampur, Dhaka",
    "Dutabash Road, Baridhara, Dhaka",
    "East Azampur, Dakshin Khan, Dhaka",
    "East Bashabo, Bashabo, Dhaka",
    "East Kazipara, Mirpur, Dhaka",
    "East Maniknagar, Maniknagar, Dhaka",
    "East Monipur, Mirpur, Dhaka",
    "East Nakhalpara, Tejgaon, Dhaka",
    "East Rampura Road, Rampura, Dhaka",
    "East Rampura, Rampura, Dhaka",
    "East Shewrapara, Mirpur, Dhaka",
    "Elephant Road, New Market, Dhaka",
    "Enayet Ganj, Hazaribag, Dhaka",
    "Fakirapool, Motijheel, Dhaka",
    "Farmgate, Tejgaon, Dhaka",
    "Faydabad, Dakshin Khan, Dhaka",
    "Free School Street, Kathalbagan, Dhaka",
    "Gajanabi Road, Mohammadpur, Dhaka",
    "Ganaktuli Road, Hazaribag, Dhaka",
    "Gandaria, Sutrapur, Dhaka",
    "Gawair, Dakshin Khan, Dhaka",
    "Girls School Road, Dakshin Khan, Dhaka",
    "Goaltek, Dakshin Khan, Dhaka",
    "Gobindapur, Jatra Bari, Dhaka",
    "Golapbag, Jatra Bari, Dhaka",
    "Golden Street, Shyamoli, Dhaka",
    "Gopibag, Motijheel, Dhaka",
    "Goran, Khilgaon, Dhaka",
    "Green City Housing, Mohammadpur, Dhaka",
    "Green Road, Kalabagan, Dhaka",
    "Green Road, Kathalbagan, Dhaka",
    "Greenway Road, Maghbazar, Dhaka",
    "Gulbag, Malibagh, Dhaka",
    "Gulshan 1, Gulshan, Dhaka",
    "Gulshan 2, Gulshan, Dhaka",
    "Haji Abdullah Sarkar Lane, Bangshal, Dhaka",
    "Haji Goli, Agargaon, Dhaka",
    "Haji Rahim Box Lane, Lalbagh, Dhaka",
    "Hazi Abdur Rashid Lane, Bangshal, Dhaka",
    "Hossain Saheb Goli, Zafrabad, Dhaka",
    "Humayun Road, Mohammadpur, Dhaka",
    "Ibrahimpur Bazar Road, Ibrahimpur, Dhaka",
    "Idgaha road, Ibrahimpur, Dhaka",
    "Imandipur, Savar, Dhaka",
    "Indira Road, Tejgaon, Dhaka",
    "Islambag, Lalbagh, Dhaka",
    "Ismail Lane, Eskaton, Dhaka",
    "Jagannathpur, Badda, Dhaka",
    "Jamoj Road, Joar Sahara, Dhaka",
    "Janata Housing Society, Adabor, Dhaka",
    "Japan Garden City, Mohammadpur, Dhaka",
    "Jhigatola Road, Dhanmondi, Dhaka",
    "Jigatola, Hazaribag, Dhaka",
    "Julon Bari, Kotwali, Dhaka",
    "Jurain, Shyampur, Dhaka",
    "Kachukhet, Dhaka",
    "Kadamtala, Bashabo, Dhaka",
    "Kadamtali, Shyampur, Dhaka",
    "Kahektuli, Bangshal, Dhaka",
    "Kajla, Jatra Bari, Dhaka",
    "Kalabagan 1st Lane, Kalabagan, Dhaka",
    "Kalabagan 2nd Lane, Kalabagan, Dhaka",
    "Kalachandpur School Road, Kalachandpur, Dhaka",
    "Kallyanpur, Mirpur, Dhaka",
    "Kamal Khan Road, Ibrahimpur, Dhaka",
    "Kamal Soroni Road, Agargaon, Dhaka",
    "Kamarpara, Turag, Dhaka",
    "Kamlapur, Motijheel, Dhaka",
    "Karatitola, Sutrapur, Dhaka",
    "Karwan Bazar, Tejgaon, Dhaka",
    "Katashur, Mohammadpur, Dhaka",
    "Katherpul, Sutrapur, Dhaka",
    "Kazi Motahar Hossain Road, Shegunbagicha, Dhaka",
    "Kazi Riaz Uddin Road, Lalbagh, Dhaka",
    "Khaje Dewan, Lalbagh, Dhaka",
    "Khajedal Sing Lane, Lalbagh, Dhaka",
    "Khan Bari Road, Kalachandpur, Dhaka",
    "Khanka E Razviya Road/Zia Soroni, Shyampur, Dhaka",
    "Khilbari Tek, Badda, Dhaka",
    "Khilji Road, Mohammadpur, Dhaka",
    "Khondokar Goli Road, Shiddheswari, Dhaka",
    "Kolta Bazar, Sutrapur, Dhaka",
    "Konapara, Demra, Dhaka",
    "Konapara, Jatra Bari, Dhaka",
    "Kosai Bari, Dakshin Khan, Dhaka",
    "Kotwali, Dhaka",
    "Krishi Bank Road, Badda, Dhaka",
    "Kutubkhali, Jatra Bari, Dhaka",
    "Kutum Goli, Agargaon, Dhaka",
    "Lake Circus Road, Kalabagan, Dhaka",
    "Lake City Concord, Khilkhet, Dhaka",
    "Lalbagh Road, Lalbagh, Dhaka",
    "Lane No 5, Mohakhali DOHS, Dhaka",
    "Lichu Bagan Road, Joar Sahara, Dhaka",
    "Luxmibazar, Sutrapur, Dhaka",
    "Madarbari, Uttar Khan, Dhaka",
    "Madartek, Bashabo, Dhaka",
    "Madhya Ajampur, Dakshin Khan, Dhaka",
    "Mahuthtuli, Bangshal, Dhaka",
    "Majed Sardar Road, Bangshal, Dhaka",
    "Majidpur, Savar, Dhaka",
    "Malibag Bazar Rd, Malibagh, Dhaka",
    "Malibag College Road, Malibagh, Dhaka",
    "Malibagh Chowdhury Para, Malibagh, Dhaka",
    "Malibagh First Lane, Malibagh, Dhaka",
    "Manda Road, Mugdapara, Dhaka",
    "Manda, Mugdapara, Dhaka",
    "Manikdi Road, Cantonment, Dhaka",
    "Manikdi, Cantonment, Dhaka",
    "Mansurabad Housing Society, Adabor, Dhaka",
    "Mastertek, Cantonment, Dhaka",
    "Matikata Road, Cantonment, Dhaka",
    "Matuail, Demra, Dhaka",
    "Meradia, Khilgaon, Dhaka",
    "Merul Badda, Badda, Dhaka",
    "Mia Para, Dakshin Khan, Dhaka",
    "Middle Badda, Badda, Dhaka",
    "Middle Bashabo, Bashabo, Dhaka",
    "Middle Monipur, Mirpur, Dhaka",
    "Middle Paikpara, Mirpur, Dhaka",
    "Mirbag Notun Rasta, Maghbazar, Dhaka",
    "Mirpur DOHS, Mirpur, Dhaka",
    "Mirpur Road, Shyamoli, Dhaka",
    "Moghbazar Kazi Office Lane, Maghbazar, Dhaka",
    "Mohammadi Homes R/A, Mohammadpur, Dhaka",
    "Mohammadi Housing LTD., Mohammadpur, Dhaka",
    "Mohammadia Housing Society, Mohammadpur, Dhaka",
    "Mohonpur Road, Shyamoli, Dhaka",
    "Momin Road, Ibrahimpur, Dhaka",
    "Moneshwar, Hazaribag, Dhaka",
    "Monipur, Mirpur, Dhaka",
    "Monipuri School Road, Ibrahimpur, Dhaka",
    "Monipuripara, Tejgaon, Dhaka",
    "Motijheel Extension, Motijheel, Dhaka",
    "Moushair, Dakshin Khan, Dhaka",
    "Mridha Bari, Kuril, Dhaka",
    "Muktijoddha Road, Kachukhet, Dhaka",
    "Muslim Modern College Road, Kachukhet, Dhaka",
    "Mymensingh Road, Shahbagh, Dhaka",
    "Nadda, Dhaka",
    "Namapara, Khilkhet, Dhaka",
    "Narinda, Sutrapur, Dhaka",
    "Nawabgonj, Lalbagh, Dhaka",
    "Nawabpur Road, Bangshal, Dhaka",
    "Naya Bazar, Bangshal, Dhaka",
    "Naya Paltan, Motijheel, Dhaka",
    "Nayatola, Maghbazar, Dhaka",
    "New Airport Road, Banani, Dhaka",
    "New Baily Road, Shiddheswari, Dhaka",
    "New Elephant Road, Hatirpool, Dhaka",
    "New Eskaton Road, Eskaton, Dhaka",
    "New Eskaton, Eskaton, Dhaka",
    "New Market, Dhaka",
    "Niketan, Road No 14/3, Niketan, Dhaka",
    "Nikunja 2, Nikunja, Dhaka",
    "Noa Nagar, Turag, Dhaka",
    "Nobodoy Housing Society, Mohammadpur, Dhaka",
    "North Adabor, Adabor, Dhaka",
    "North Azampur, Dakshin Khan, Dhaka",
    "North Bashabo, Bashabo, Dhaka",
    "North Dhanmondi Road, Kalabagan, Dhaka",
    "North Goran, Khilgaon, Dhaka",
    "North Ibrahimpur, Ibrahimpur, Dhaka",
    "North Jatra Bari, Jatra Bari, Dhaka",
    "North Kafrul Road, Ibrahimpur, Dhaka",
    "North Kafrul Road, Ibrahimpur, Dhaka",
    "North Mugdapara, Mugdapara, Dhaka",
    "North Road, Dhanmondi, Dhaka",
    "North Shahjahanpur, Shahjahanpur, Dhaka",
    "Nurer Chala, Badda, Dhaka",
    "Nurjahan Road, Mohammadpur, Dhaka",
    "Old Eskaton, Eskaton, Dhaka",
    "Outer Circular Road, Maghbazar, Dhaka",
    "Outer Circular Road, Shiddheswari, Dhaka",
    "Paikpara, Mirpur, Dhaka",
    "Pallabi, Mirpur, Dhaka",
    "Panthapath, Kathalbagan, Dhaka",
    "Park Road, Baridhara, Dhaka",
    "PC Culture Housing, Mohammadpur, Dhaka",
    "Pearabagh Road, Maghbazar, Dhaka",
    "Pearl Street, Shyamoli, Dhaka",
    "Peer Saheber Goli, Shantinagar, Dhaka",
    "Pirerbag, Mirpur, Dhaka",
    "Police Fari road, Khilgaon, Dhaka",
    "Poribagh Road Number 2, Paribagh, Dhaka",
    "Postagola, Shyampur, Dhaka",
    "Pragati Soroni, Kuril, Dhaka",
    "Primary school Road, Ibrahimpur, Dhaka",
    "Purana Paltan, Motijheel, Dhaka",
    "Rajabazar, Tejgaon, Dhaka",
    "Rajarbag, Bashabo, Dhaka",
    "Rajarbagh, Motijheel, Dhaka",
    "Rajia Sultana Road, Mohammadpur, Dhaka",
    "Ranavola Road, Turag, Dhaka",
    "Rayer Bazaar, Hazaribag, Dhaka",
    "rayer bazar-sanker road, Dhanmondi, Dhaka",
    "Road No 1, Banani, Dhaka",
    "Road No 1, Baridhara DOHS, Dhaka",
    "Road No 1, Baridhara, Dhaka",
    "Road No 1, Dhanmondi, Dhaka",
    "Road No 1, Shyamoli, Dhaka",
    "Road No 10, Baridhara DOHS, Dhaka",
    "Road No 10, Dhanmondi, Dhaka",
    "Road No 10A, Dhanmondi, Dhaka",
    "Road No 10B, Banani, Dhaka",
    "Road No 11, Baridhara, Dhaka",
    "Road No 11A, Dhanmondi, Dhaka",
    "Road No 12, Baridhara, Dhaka",
    "Road No 12, Dhanmondi, Dhaka",
    "Road No 12A, Dhanmondi, Dhaka",
    "Road No 13, Banani, Dhaka",
    "Road No 13, Baridhara, Dhaka",
    "Road No 14, Banani, Dhaka",
    "Road No 14A, Dhanmondi, Dhaka",
    "Road No 15, Dhanmondi, Dhaka",
    "Road No 16, Banani, Dhaka",
    "Road No 16, Dhanmondi, Dhaka",
    "Road No 18, Banani, Dhaka",
    "Road No 19, Mohakhali DOHS, Dhaka",
    "Road No 2, Banani, Dhaka",
    "Road No 2, Baridhara DOHS, Dhaka",
    "Road No 2, Dhanmondi, Dhaka",
    "Road No 2, Shyamoli, Dhaka",
    "Road No 21, Banani, Dhaka",
    "Road No 23, Mohakhali DOHS, Dhaka",
    "Road No 28, Banani, Dhaka",
    "Road No 2A, Cantonment, Dhaka",
    "Road No 2A, Dhanmondi, Dhaka",
    "Road No 3, Banani, Dhaka",
    "Road No 3, Baridhara, Dhaka",
    "Road No 3, Dhanmondi, Dhaka",
    "Road No 3, Niketan, Dhaka",
    "Road No 3A, Dhanmondi, Dhaka",
    "Road No 4, Banani DOHS, Dhaka",
    "Road No 4, Banani, Dhaka",
    "Road No 4, Baridhara DOHS, Dhaka",
    "Road No 4, Dhanmondi, Dhaka",
    "Road No 4, Shyamoli, Dhaka",
    "Road No 4A, Dhanmondi, Dhaka",
    "Road No 5, Banani, Dhaka",
    "Road No 5, Baridhara, Dhaka",
    "Road No 5, Dhanmondi, Dhaka",
    "Road No 6, Banani DOHS, Dhaka",
    "Road No 6, Baridhara DOHS, Dhaka",
    "Road No 6, Baridhara, Dhaka",
    "Road No 6, Niketan, Dhaka",
    "Road No 6A, Dhanmondi, Dhaka",
    "Road No 7, Banani, Dhaka",
    "Road No 7, Baridhara DOHS, Dhaka",
    "Road No 7, Dhanmondi, Dhaka",
    "Road No 7A, Dhanmondi, Dhaka",
    "Road No 8A, Dhanmondi, Dhaka",
    "Road No 9, Adabor, Dhaka",
    "Road No 9, Baridhara DOHS, Dhaka",
    "Road No 9, Niketan, Dhaka",
    "Road No 9A, Dhanmondi, Dhaka",
    "Rupnagar R/A, Mirpur, Dhaka",
    "Saat Rawza, Bangshal, Dhaka",
    "Sadek Khan Road, Hazaribag, Dhaka",
    "Salimuddin Market Road, Mirpur, Dhaka",
    "Salimullah Road, Mohammadpur, Dhaka",
    "Sarulia, Demra, Dhaka",
    "Sat Masjid Housing, Mohammadpur, Dhaka",
    "School Road, Mohakhali, Dhaka",
    "Science Museum To Water Tank Road, Agargaon, Dhaka",
    "Section 1, Mirpur, Dhaka",
    "Section 10, Mirpur, Dhaka",
    "Section 11, Mirpur, Dhaka",
    "Section 12, Mirpur, Dhaka",
    "Section 13, Mirpur, Dhaka",
    "Section 15, Mirpur, Dhaka",
    "Section 2, Mirpur, Dhaka",
    "Section 6, Mirpur, Dhaka",
    "Section 7, Mirpur, Dhaka",
    "Sector 1, Uttara, Dhaka",
    "Sector 10, Uttara, Dhaka",
    "Sector 11, Uttara, Dhaka",
    "Sector 12, Uttara, Dhaka",
    "Sector 13, Uttara, Dhaka",
    "Sector 14, Uttara, Dhaka",
    "Sector 15, Uttara, Dhaka",
    "Sector 17, Uttara, Dhaka",
    "Sector 18, Uttara, Dhaka",
    "Sector 3, Uttara, Dhaka",
    "Sector 4, Uttara, Dhaka",
    "Sector 5, Uttara, Dhaka",
    "Sector 6, Uttara, Dhaka",
    "Sector 7, Uttara, Dhaka",
    "Sector 9, Uttara, Dhaka",
    "Shah Kabir Mazar Road, Dakshin Khan, Dhaka",
    "Shahbagh Road, Paribagh, Dhaka",
    "Shaheed Tajuddin Ahmed Ave, Maghbazar, Dhaka",
    "Shahid Latif Road, Dakshin Khan, Dhaka",
    "Shahid Nagar, Lalbagh, Dhaka",
    "Shahid Syed Nazrul Islam Sharani, Motijheel, Dhaka",
    "Shahjadpur, Badda, Dhaka",
    "Shahjahan Road, Mohammadpur, Dhaka",
    "Shamibag, Sutrapur, Dhaka",
    "Shantibag - Shahidbag Road, Malibagh, Dhaka",
    "Shantibag, Malibagh, Dhaka",
    "Shantinagar Bazar Rd, Shantinagar, Dhaka",
    "Shantinagar Road, Shantinagar, Dhaka",
    "Shegunbagicha Road, Shegunbagicha, Dhaka",
    "Sheikhdi, Jatra Bari, Dhaka",
    "Shekhertek, Mohammadpur, Dhaka",
    "Sher Shah Suri Road, Mohammadpur, Dhaka",
    "Sher-E-Bangla Road, Dhanmondi, Dhaka",
    "Sher-E-Bangla Road, Hazaribag, Dhaka",
    "Sher-E-Bangla Road, Mohammadpur, Dhaka",
    "Shiddeswari Road, Shiddheswari, Dhaka",
    "Shiddheswari Lane, Shiddheswari, Dhaka",
    "Shonir Akhra, Shyampur, Dhaka",
    "Shukrabad, Dhanmondi, Dhaka",
    "Shyamoli Housing (2nd Project), Adabor, Dhaka",
    "Sir Sayed Road, Mohammadpur, Dhaka",
    "Sobhanbag, Savar, Dhaka",
    "Sohrawardy Avenue, Baridhara, Dhaka",
    "Sonatongor Masjid Road, Hazaribag, Dhaka",
    "South Azampur, Dakshin Khan, Dhaka",
    "South Badda, Badda, Dhaka",
    "South Banasree Project, Banasree, Dhaka",
    "South Baridhara Residential Area,D.I.T. Project, Badda, Dhaka",
    "South Bashabo, Bashabo, Dhaka",
    "South Chalabon, Dakshin Khan, Dhaka",
    "South Jatra Bari, Jatra Bari, Dhaka",
    "South Kafrul Road, Kafrul, Dhaka",
    "South Keraniganj, Keraniganj, Dhaka",
    "South Mollartek, Dakshin Khan, Dhaka",
    "South Monipur, Mirpur, Dhaka",
    "South Mugdapara, Mugdapara, Dhaka",
    "Srjani road, Ibrahimpur, Dhaka",
    "Sultangong Road, Hazaribag, Dhaka",
    "Tajmahal Road, Mohammadpur, Dhaka",
    "Tali office Road, Hazaribag, Dhaka",
    "Tallabag, Hazaribag, Dhaka",
    "Taltola goli, Maghbazar, Dhaka",
    "Taltola, Agargaon, Dhaka",
    "Taltola, Dakshin Khan, Dhaka",
    "Taltola, Khilgaon, Dhaka",
    "Tejgaon Industrial Area, Tejgaon, Dhaka",
    "Tejkunipara, Tejgaon, Dhaka",
    "Tikatuli, Sutrapur, Dhaka",
    "Tikka Para Road, Mohammadpur, Dhaka",
    "Tilpapara, Khilgaon, Dhaka",
    "Titas Gas Road, Rampura, Dhaka",
    "Titas Gas Road, Shyampur, Dhaka",
    "Topkhana Road, Shegunbagicha, Dhaka",
    "Turag, Dhaka",
    "Ullan, Rampura, Dhaka",
    "Uttar Badda, Badda, Dhaka",
    "Uttar Khan, Dhaka",
    "Vashantek, Cantonment, Dhaka",
    "Vatara, Badda, Dhaka",
    "Ward 98, Rampura, Dhaka",
    "Wari, Sutrapur, Dhaka",
    "Wasa Road, Mugdapara, Dhaka",
    "West Agargaon, Agargaon, Dhaka",
    "West Dhanmondi and Shangkar, Dhanmondi, Dhaka",
    "West Dhanmondi, Dhanmondi, Dhaka",
    "West Dolairpar, Shyampur, Dhaka",
    "West End Street, Hatirpool, Dhaka",
    "West Kafrul, Taltola, Dhaka",
    "West Kazipara, Mirpur, Dhaka",
    "West Malibag, Malibagh, Dhaka",
    "West Mollartek, Dakshin Khan, Dhaka",
    "West Monipur, Mirpur, Dhaka",
    "West Nakhalpara, Tejgaon, Dhaka",
    "West Rampura, Rampura, Dhaka",
    "West Shewrapara, Mirpur, Dhaka",
    "Zafrabad, Hazaribag, Dhaka",
    "Zindabahar 2nd Lane, Kotwali, Dhaka"
]